channels:
- defaults
- conda-forge
- pytorch
dependencies:
- python=3.8.2
- pytorch==1.7.1+cpu
- pip
- pip:
  - mlflow
  - scikit-learn
  - cloudpickle==1.6.0
  - boto3
  - transformers==4.0.0
  - torchtext==0.7.0
  - pandas
