channels:
- defaults
- conda-forge
- pytorch
dependencies:
- python=3.8.2
- pip
- pytorch-cpu=1.7.1
- pip:
  - mlflow
  - scikit-learn
  - cloudpickle==1.6.0
  - boto3
  - transformers==4.0.0
  - torchtext==0.7.0
  - pandas
