name: "Deploy model to TorchServe"

on:
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      GCP_CREDS_JSON_BASE64: ${{ secrets.GCP_CREDS_JSON_BASE64 }}
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2
      - name: Get Tag name
        uses: little-core-labs/get-git-tag@v3.0.1
        id: tag_name
        with:
          tagRegex: ".*(BertModel-\\d+).*"
      - name: Create Cloud Run label
        run: echo ::set-output name=label::$(echo ${{ steps.tag_name.outputs.tag }} |  tr '[:upper:]' '[:lower:]')
        id: prepare_label
      - name: Setup Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Deploy to Google Cloud Run
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: engineeringlab
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        with:
          args: |
            run deploy news-bert-service --image gcr.io/engineeringlab/torchserve:${{ steps.tag_name.outputs.tag }} --platform managed --port 8080 --allow-unauthenticated --memory 2G --cpu 2 --region southamerica-east1 --update-labels=model=${{ steps.prepare_label.outputs.label }}
